### ISSUE TITLE
Display brightness controls?

### ISSUE THREAD

**Issue by MenacingPerson** [Prayag2/kde_controlcentre#1]
I think it's self-explanatory

**Comment by MenacingPerson** [comment]
```
percentage=50
max="$(qdbus org.kde.Solid.PowerManagement /org/kde/Solid/PowerManagement/Actions/BrightnessControl brightnessMax)"
xyz=$((percentage*max/100))
qdbus org.kde.Solid.PowerManagement /org/kde/Solid/PowerManagement/Actions/BrightnessControl setBrightness $xyz
```

**Comment by Prayag2** [comment]
I actually created a brightness slider but I don't have a monitor that supports changing brightness via software so I can't really make it work.

**Comment by linusrg1** [comment]
> I actually created a brightness slider but I don't have a monitor that supports changing brightness via software so I can't really make it work.

First I want to say I suck at coding, I just want to put that out there. But I do use a laptop. So if you want to attempt to implement brightness functionality and then give me a test build to test out, I would be more than happy to. I know it would not be the most practical of ways to go about things, because you would have to create a build, have me test it, and then have me report back on weather it worked or not. If it didn't, I would need to go ahead and tell you how it isn't working as well as provide logs for you to use. 


Thanks for this widget though, its really awesome! While I like KDE Breeze's look better, especially because of how customizable Breeze is now. I have always found the layout of macOS to be more practical than other desktop layouts, say for the apple menu and launchpad anyway, and this widget completes that functionality I liked from macOS! I also personally think KDE's Application Launcher is much more practical than an apple menu/launchpad combo, a lot more useful, and a lot more organized tbh. I also use a hidden panel on the left as a dock, because it is more practical than a dock on the bottom of your screen, and/or a permanently visible one. In my opinion, anyway.

Sorry for rambling in the end here. Basically I just wanted to say, I like your widget, and if you want help testing brightness functionality I'd be happy to! Even if regretfully, I cannot help with the programming area of things.

**Comment by MenacingPerson** [comment]
Maybe look at the code for the `Battery and Brightness` widget in KDE?

**Comment by onuralpszr** [comment]
@Prayag2 please assign me I did brightness work (I can change it, I am starting MR)
